name: Deploy Spring Boot to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3️⃣ gradlew 실행 권한 부여
      - name: Grant execute permission
        run: chmod +x ./gradlew

      # 4️⃣ Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 5️⃣ rsync로 빌드된 JAR EC2로 전송 (압축 없이 단일 파일 전송)
      - name: Copy jar to EC2 with rsync
        run: |
          rsync -avz -e "ssh -i ${{ secrets.EC2_PRIVATE_KEY }}" build/libs/shop-0.0.1-SNAPSHOT.jar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app/
