name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main   # main 브랜치에 push 될 때만 배포 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3️⃣ Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 4️⃣ 빌드된 JAR EC2로 전송
      - name: Upload jar to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "build/libs/*.jar"
          target: "~/app"

      # 5️⃣ EC2에 접속해 서버 재시작
      - name: Deploy and restart app on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "✅ 기존 애플리케이션 종료 중..."
            pkill -f 'java -jar' || true

            echo "✅ 새 애플리케이션 실행 중..."
            nohup java -jar ~/app/*.jar > ~/app/log.out 2>&1 &

            echo "✅ 배포 완료!"
